### ISSUE TITLE
Завершение разметки проекта

### ISSUE THREAD

**Issue by tatyanabak** [bak-tanya/74274-cat-energy-16#7]
Завершить:
- [x] index.html ("Живой пример")
- [x] page-footer (карта и адрес)
- [x]  form.html (все)

branch module2-task2

@ademaro, welcome найти десяток косяков! )

**Comment by ademaro** [comment]
ПР можно закрывать, думаю... https://github.com/htmlacademy-adaptive/74274-cat-energy-16/pull/3#pullrequestreview-223529761

ПР в этой репе (#8) сделал для тестирования, пока закрою (после закрытия ПР в главной репе), но давай третью ветку попробуем тож тут сделать (ПР не только в главную репу мастера пойдёт, но и сюда тож), посмотрим как будут вести себя нотификации).
