### ISSUE TITLE
Переименовать лейблы

### ISSUE THREAD

**Issue by ademaro** [bak-tanya/74274-cat-energy-16#9]
Раз у нас проект русоязычный, коммиты, сами ишки всё на русском, то можно и лейблы сделать адаптированными и более единообразными.  @bak-tanya, что думаешь?

**Comment by tatyanabak** [comment]
Готово!

**Comment by ademaro** [comment]
Я бы не просто перевёл, а именно адаптировал) Удалил ненужные, добавил бы, которые могут потребоваться... Но это не срочно, в течение интенсива сможем дорабатывать этот момент...

**Comment by tatyanabak** [comment]
Ок, услышано.
Тогда готовься к лейблам из серии "Антон, всё очень плохо" )
